//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKUTUPHANEEntities1 : DbContext
    {
        public DBKUTUPHANEEntities1()
            : base("name=DBKUTUPHANEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TBLCEZALAR> TBLCEZALAR { get; set; }
        public DbSet<TBLHAREKET> TBLHAREKET { get; set; }
        public DbSet<TBLKASA> TBLKASA { get; set; }
        public DbSet<TBLKATEGORİ> TBLKATEGORİ { get; set; }
        public DbSet<TBLKİTAP> TBLKİTAP { get; set; }
        public DbSet<TBLPERSONEL> TBLPERSONEL { get; set; }
        public DbSet<TBLUYELER> TBLUYELER { get; set; }
        public DbSet<TBLYAZAR> TBLYAZAR { get; set; }
    }
}
