//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLYAZAR
    {
        public TBLYAZAR()
        {
            this.TBLKİTAP = new HashSet<TBLKİTAP>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Yazar Adını Boş Geçemezsiniz")]
        public string AD { get; set; }
        [StringLength(20,ErrorMessage ="Soyad 20 Karakterden Uzun Olamaz")]
        public string SOYAD { get; set; }
        public string DETAY { get; set; }
    
        public virtual ICollection<TBLKİTAP> TBLKİTAP { get; set; }
    }
}
